#!/usr/bin/env python3
"""generate_status_stubs.py -- SHP-7: retire the abandoned manual status docs.

SHP-7 of the status/history plane-separation design
(evidence/planning/status_history_plane_separation_design.md, Sec.1 "Two doc
populations, unlabelled" + status table Sec.7).

Kills the third "looks-maintained-but-isn't" doc category. Three docs had NO
generator owning them and were rotting silently -- a cold-start reader (human or
agent) could not tell stale hand-prose from current state. This script becomes
their owner: it regenerates each one, GENERATED-marked and timestamped, every
governance run, so currency is never in doubt.

  - evidence/GOVERNANCE_STATE.md  last hand-touched 2026-03 (V1/V2 era). Its
        "current governance state" is now derived continuously by the governance
        pipeline; the closed SD-001/002/003 substrate-debt register and the Q-019
        three-gate hypothesis survive in the architecture docs + claims.yaml + git.
        -> RETIRED to a generated pointer stub.
  - docs/REE_overview.md          IMPL-004, now status:legacy in claims.yaml. A
        secondary orientation summary over the canonical architecture docs.
        -> RETIRED to a generated pointer stub (keeps the #impl-004 anchor so the
        claims.yaml `location:` link still resolves; keeps nav_exclude).
  - docs/index.md                 the public Jekyll (Just-the-Docs) Home page. Its
        narrative is timeless; only the dated "Latest result" block rotted.
        -> REGENERATED: narrative preserved (now owned + stamped here), the rotting
        block replaced by a live pointer to docs/CURRENT_FRONT.md. Stays a valid
        Home page (title:Home / nav_order:1).

PROMOTES / DEMOTES NOTHING. Read-only over the repo; only writes the three docs.

ORDERING CONTRACT: run in scripts/governance.sh BEFORE docs/apply_nav_frontmatter.py.
That stamper owns each docs/ page's nav frontmatter (index.md -> title:Home,
nav_order:1; REE_overview.md -> nav_exclude:true) and PRESERVES the body this script
writes, so the two co-operate: this script owns the bodies, the stamper owns the
frontmatter. GOVERNANCE_STATE.md lives under evidence/ and the nav stamper never
touches it.

ASCII-only stdout (Windows cp1252 safety). UTF-8 file bodies are fine.

Usage (from REE_assembly root, or anywhere):
    python scripts/generate_status_stubs.py
Runs automatically in scripts/governance.sh.
"""

import os
import sys
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

GOVERNANCE_STATE = os.path.join(ROOT, "evidence", "GOVERNANCE_STATE.md")
REE_OVERVIEW = os.path.join(ROOT, "docs", "REE_overview.md")
INDEX = os.path.join(ROOT, "docs", "index.md")

GEN_MARK = ("<!-- GENERATED FILE -- do not edit by hand. "
            "Regenerated by scripts/generate_status_stubs.py (SHP-7). -->")


def render_governance_state(now):
    """evidence/GOVERNANCE_STATE.md -- retired to a live-source pointer stub."""
    return """# Governance State -- RETIRED (generated stub)

%s

> **GENERATED -- do not edit by hand.** Regenerated by
> `scripts/generate_status_stubs.py` (runs in `scripts/governance.sh`).  \n> Generated: %s

This file was a hand-maintained snapshot last meaningfully updated **2026-03**
(the V1/V2 era). It is **retired**: its "current governance state" is now derived
continuously by the governance pipeline. Do not read the old prose as current --
it no longer has a maintainer, and the live state lives in the sources below.

## Where the live governance state is now

- Promotion / demotion recommendations (incl. synthetic-data flags):
  [experiments/promotion_demotion_recommendations.md](experiments/promotion_demotion_recommendations.md)
- Experiments awaiting review:
  [experiments/pending_review.md](experiments/pending_review.md)
- Evidence matrix / per-claim run counts:
  [experiments/INDEX.md](experiments/INDEX.md)
- Closure rollup + drift:
  [planning/closure_status.md](planning/closure_status.md) /
  [planning/closure_drift.md](planning/closure_drift.md)
- The single live front of progress:
  [../docs/CURRENT_FRONT.md](../docs/CURRENT_FRONT.md)
- Claim registry (status of every claim):
  [../docs/claims/claims.yaml](../docs/claims/claims.yaml)

## What the retired content was (and where it lives now)

- The V1/V2 genuine-evidence corpus snapshot + per-claim run counts -- superseded
  by the live evidence matrix (`experiments/INDEX.md`, `claim_evidence.v1.json`).
- The synthetic-contamination flag -- now emitted per-claim in
  `experiments/promotion_demotion_recommendations.md`.
- The SD-001 / SD-002 / SD-003 substrate-debt register (all **closed** in ree-v2)
  -- captured in the architecture docs (`docs/architecture/*`) and
  `docs/changelog.md`.
- The Q-019 three-gate basal-ganglia hypothesis -- registered as claim **Q-019**
  (`docs/claims/claims.yaml`) and documented in
  `docs/architecture/three_loop_learning_channels.md`,
  `docs/architecture/agency_responsibility_flow.md`, and related pages.

The full prior hand-written text remains in this path's **git history**.
""" % (GEN_MARK, now)


def render_ree_overview(now):
    """docs/REE_overview.md -- retired to a canonical-sources pointer stub.

    Keeps the #impl-004 anchor (claims.yaml IMPL-004 `location:` links here) and
    the nav_exclude frontmatter (matches apply_nav_frontmatter.py TOP_EXCLUDE).
    """
    return """---
nav_exclude: true
---

# REE Overview -- RETIRED (generated stub)

%s
<a id="impl-004"></a>

> **GENERATED -- do not edit by hand.** Regenerated by
> `scripts/generate_status_stubs.py` (runs in `scripts/governance.sh`).  \n> Generated: %s

This was a secondary, hand-maintained orientation summary (claim **IMPL-004**, now
`status: legacy` in `docs/claims/claims.yaml`). It is **retired** so there is not a
second, silently-drifting copy of the canonical architecture. Read the canonical
sources instead:

## Orientation -- canonical sources

- **Why REE exists / the axioms:**
  [Foundations](architecture/five_axioms_foundations.md)
- **How the architecture is derived from ethics:**
  [Why This Architecture?](architecture/ethical_agency_derivation.md)
- **Why alignment must live inside the generator:**
  [Post-Hoc Filter Insufficiency](architecture/post_hoc_filter_insufficiency.md)
- **Component architecture:** [Architecture overview](architecture/overview.md) ->
  [E1](architecture/e1.md), [E2](architecture/e2.md), [E3](architecture/e3.md),
  [Control Plane](architecture/control_plane.md),
  [Hippocampal Systems](architecture/hippocampal_systems.md)
- **Site home / alignment framing:** [Home](index.md)
- **Programme phases + current experiment state:** [Roadmap](roadmap.md)
- **The single live front of progress:** [CURRENT_FRONT.md](CURRENT_FRONT.md)
- **Registered claims:** [Claims index](claims/claim_index.md) /
  [claims.yaml](claims/claims.yaml)
""" % (GEN_MARK, now)


# The public home page narrative below is TIMELESS (axioms, alignment framing,
# where-to-start routing). It is owned + stamped HERE so it is no longer unowned
# hand-prose; the one element that rotted -- a dated "Latest result" block -- is
# replaced by a live pointer to the generated CURRENT_FRONT.md. Edit the home page
# by editing THIS template, not docs/index.md (which is regenerated every run).
INDEX_BODY = """<div class="ree-home">
  <section class="ree-hero" aria-labelledby="ree-title">
    <img class="ree-hero-image" src="{{ '/architecture/brain_sagittal.jpg' | relative_url }}" alt="Sagittal brain image illustrating REE's neuroscience validation path.">
    <div class="ree-shell">
      <p class="ree-kicker">Latent Fields research programme</p>
      <div class="ree-home-heading-1" id="ree-title" role="heading" aria-level="1">Reflective-Ethical Engine</div>
      <p class="ree-hero-deck">
        REE asks what architecture an agent needs in order to act ethically, and
        whether that architecture can be derived from first principles rather
        than designed by hand.
      </p>
      <p class="ree-research-disclosure">
        Exploratory research materials: no REE manuscript or related work has
        been accepted for peer-reviewed publication. <a href="{{ '/research_status.html' | relative_url }}">Read the research status</a>.
      </p>
      <div class="ree-milestone-callout" role="note" aria-label="Programme milestone, 29 August 2026">
        <p class="ree-milestone-kicker">Milestone -- 29 August 2026</p>
        <p class="ree-milestone-headline"><strong>Viable minimal working intelligence achieved; causal/ablative validation of the responsible architecture remains incomplete.</strong></p>
        <p class="ree-milestone-body">
          REE-v3 now demonstrates enough learned, integrated behavioural competence to serve as a working organism for higher-order mechanistic experiments. This is a working programme milestone, not peer-reviewed validation -- it does not assert general intelligence, consciousness, sentience, or that the REE architecture is necessary or sufficient for the competencies observed.
          Read the <a href="https://github.com/Latent-Fields/REE_assembly/blob/master/docs/thoughts/2026-08-29_MILESTONE_viable_minimal_working_intelligence_achieved.md">milestone declaration</a> and the <a href="{{ '/CURRENT_FRONT.html' | relative_url }}">current evidence and closure view</a>.
        </p>
      </div>
      <p class="ree-hero-thesis">
        The core claim is that alignment belongs inside the generative machinery
        of agency: harm modelling, agency attribution, goal persistence,
        uncertainty, and care must shape the state from which candidate futures
        are generated, not merely score those futures after generation.
      </p>
      <div class="ree-actions" aria-label="Primary links">
        <a class="ree-button ree-button-primary" href="{{ '/architecture/ethical_agency_derivation.html' | relative_url }}">Start with the derivation</a>
        <a class="ree-button ree-button-secondary" href="{{ '/public_explorer/' | relative_url }}">Open the Lab Window</a>
      </div>
      <div class="ree-validation-chain" aria-label="REE validation chain">
        <span>axioms</span>
        <span>necessary comparators</span>
        <span>neuroscience convergence</span>
        <span>clinical failure modes</span>
        <span>claim-governed evidence</span>
      </div>
    </div>
  </section>

  <section class="ree-band">
    <div class="ree-shell">
      <div class="ree-section-heading">
        <p class="ree-kicker">What changes</p>
        <div class="ree-home-heading-2" role="heading" aria-level="2">Ethics becomes a substrate question.</div>
      </div>
      <div class="ree-card-grid ree-card-grid-three">
        <article class="ree-card">
          <div class="ree-home-heading-3" role="heading" aria-level="3">Not a rule layer</div>
          <p>REE does not begin by specifying desired behaviour and training toward it. It asks which computational capacities cannot be absent if an agent is to act in a world at all.</p>
        </article>
        <article class="ree-card">
          <div class="ree-home-heading-3" role="heading" aria-level="3">Not a post-hoc filter</div>
          <p>A sufficiently capable optimiser can learn to satisfy or explain a proxy while leaving its generator unchanged. REE places constraint-relevant content inside state construction, trajectory generation, commitment, and memory.</p>
        </article>
        <article class="ree-card">
          <div class="ree-home-heading-3" role="heading" aria-level="3">Not only philosophy</div>
          <p>The derivation is cross-checked against neuroscience and psychiatric breakdowns. Missing structures should fail in recognisable ways if the architecture is genuinely necessary.</p>
        </article>
      </div>
    </div>
  </section>

  <section class="ree-band ree-band-muted">
    <div class="ree-shell ree-split">
      <div>
        <p class="ree-kicker">Derived architecture</p>
        <div class="ree-home-heading-2" role="heading" aria-level="2">What the derivation found</div>
        <p class="ree-lead">
          Starting from foundational axioms, REE derives a compact set of
          structures that ethical agency cannot do without. Remove one, and a
          specific ethical function disappears.
        </p>
      </div>
      <div class="ree-component-list" aria-label="Core REE components">
        <a href="{{ '/architecture/e1.html' | relative_url }}"><strong>E1</strong><span>persistent world and self model</span></a>
        <a href="{{ '/architecture/e2.html' | relative_url }}"><strong>E2</strong><span>fast transition and affordance predictor</span></a>
        <a href="{{ '/architecture/e3.html' | relative_url }}"><strong>E3</strong><span>trajectory selection and commitment</span></a>
        <a href="{{ '/architecture/control_plane.html' | relative_url }}"><strong>Control plane</strong><span>precision, gain, uncertainty, and mode regulation</span></a>
        <a href="{{ '/architecture/hippocampal_systems.html' | relative_url }}"><strong>Hippocampal systems</strong><span>multi-step rollout, map, replay, and residue handling</span></a>
      </div>
    </div>
  </section>

  <section class="ree-band">
    <div class="ree-shell">
      <div class="ree-section-heading">
        <p class="ree-kicker">Why it matters</p>
        <div class="ree-home-heading-2" role="heading" aria-level="2">The same absences predict AI alignment failures and biological regime breakdowns.</div>
      </div>
      <div class="ree-evidence-row">
        <div class="ree-evidence-item">
          <span>01</span>
          <div class="ree-home-heading-3" role="heading" aria-level="3">Neuroscience convergence</div>
          <p>The offline consolidation phase maps onto two-stage sleep; commitment gating maps onto basal-ganglia circuitry; harm accumulation maps onto cingulate and serotonergic modulation.</p>
        </div>
        <div class="ree-evidence-item">
          <span>02</span>
          <div class="ree-home-heading-3" role="heading" aria-level="3">Psychiatric validation path</div>
          <p>If capacities are necessary, their failure should produce structured breakdowns: depression, dementia, OCD, mania, psychosis, and related disturbances become tests of the substrate.</p>
        </div>
        <div class="ree-evidence-item">
          <span>03</span>
          <div class="ree-home-heading-3" role="heading" aria-level="3">Evidence discipline</div>
          <p>REE claims are typed, registered, confidence-scored, and governed through an experiment-evidence pipeline rather than maintained as loose prose.</p>
        </div>
      </div>
    </div>
  </section>

  <section class="ree-band ree-band-muted">
    <div class="ree-shell">
      <div class="ree-section-heading">
        <p class="ree-kicker">Reader routes</p>
        <div class="ree-home-heading-2" role="heading" aria-level="2">Start at the right depth.</div>
      </div>
      <div class="ree-route-grid">
        <a class="ree-route-card" href="{{ '/architecture/ethical_agency_derivation.html' | relative_url }}">
          <span>New to REE</span>
          <strong>Why This Architecture?</strong>
          <p>The derivation in full, the cognifold motif, and why the brain result matters.</p>
        </a>
        <a class="ree-route-card" href="{{ '/architecture/what_is_ree_made_of.html' | relative_url }}">
          <span>Whole-system picture</span>
          <strong>What Is REE Made Of?</strong>
          <p>Learned structure, moment-to-moment activity, persistent state, and explicit dynamics -- before the mechanism inventory.</p>
        </a>
        <a class="ree-route-card" href="{{ '/architecture/post_hoc_filter_insufficiency.html' | relative_url }}">
          <span>Alignment framing</span>
          <strong>Post-Hoc Filter Insufficiency</strong>
          <p>Why safety and ethical content must be active inside trajectory generation.</p>
        </a>
        <a class="ree-route-card" href="{{ '/architecture/five_axioms_foundations.html' | relative_url }}">
          <span>Foundations</span>
          <strong>Five Axioms</strong>
          <p>The irreducible commitments from which the architecture follows.</p>
        </a>
        <a class="ree-route-card" href="{{ '/public_explorer/' | relative_url }}">
          <span>Evidence</span>
          <strong>Lab Window</strong>
          <p>A read-only public view of reviewed claims, mechanisms, and experiments.</p>
        </a>
        <a class="ree-route-card" href="{{ '/ree_for_my_parents.html' | relative_url }}">
          <span>Gentlest introduction</span>
          <strong>REE for My Parents</strong>
          <p>A plain-language account of what REE is, what has actually been built, and why the project matters.</p>
        </a>
        <a class="ree-route-card" href="{{ '/ree_for_psychiatrists.html' | relative_url }}">
          <span>Clinical route</span>
          <strong>REE for Psychiatrists</strong>
          <p>The substrate-failure interpretation of clinical and computational regimes.</p>
        </a>
        <a class="ree-route-card" href="{{ '/glossary.html' | relative_url }}">
          <span>Terminology</span>
          <strong>Glossary</strong>
          <p>Canonical terms before the component documents become too dense.</p>
        </a>
        <a class="ree-route-card" href="{{ '/related_work.html' | relative_url }}">
          <span>Programme map</span>
          <strong>Related Latent-Fields Work</strong>
          <p>Manuscript drafts, prototypes, research versions, and adjacent projects with explicit status labels.</p>
        </a>
      </div>
    </div>
  </section>

  <section class="ree-band">
    <div class="ree-shell ree-status-panel">
      <div>
        <p class="ree-kicker">Live programme state</p>
        <div class="ree-home-heading-2" role="heading" aria-level="2">The current front is generated, not hand-maintained.</div>
        <p class="ree-lead">
          For the single live front of progress, with no history mixed in, read
          the generated Current Front. Narrative history remains in the
          changelog, and the claims registry remains the evidence source of truth.
        </p>
      </div>
      <div class="ree-link-list">
        <a href="{{ '/CURRENT_FRONT.html' | relative_url }}">Current Front</a>
        <a href="{{ '/claims/claim_index.html' | relative_url }}">Claims index</a>
        <a href="{{ '/roadmap.html' | relative_url }}">Roadmap</a>
        <a href="{{ '/contribute.html' | relative_url }}">Contribute compute</a>
      </div>
    </div>
  </section>

  <section class="ree-band ree-final-band">
    <div class="ree-shell">
      <p class="ree-kicker">Implementation substrates</p>
      <div class="ree-substrate-grid" aria-label="REE implementation substrates">
        <div><strong>ree-v3</strong><span>active primary implementation and experiment substrate</span></div>
        <div><strong>ree-v2</strong><span>complete 15-experiment predecessor; triggered the V3 transition</span></div>
        <div><strong>ree-v1-minimal</strong><span>active baseline and parity substrate</span></div>
      </div>
      <p class="ree-credit"><a href="{{ '/substrate_versions.html' | relative_url }}">What each substrate generation is for, and how they build on each other &rarr;</a></p>
      <p class="ree-credit">REE is developed by Daniel Golden (Latent Fields). Licensed under Apache 2.0.</p>
    </div>
  </section>
</div>
"""


def render_index(now):
    """docs/index.md -- regenerated public Home page (nav frontmatter first)."""
    frontmatter = "---\ntitle: Home\nnav_order: 1\n---\n"
    header = ("%s\n<!-- Home page body is owned + regenerated by "
              "scripts/generate_status_stubs.py (SHP-7); Generated: %s. "
              "Edit the INDEX_BODY template in that script, not this file. "
              "apply_nav_frontmatter.py owns the frontmatter above. -->\n"
              % (GEN_MARK, now))
    return frontmatter + header + "\n" + INDEX_BODY


def main():
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    outputs = [
        (GOVERNANCE_STATE, render_governance_state(now)),
        (REE_OVERVIEW, render_ree_overview(now)),
        (INDEX, render_index(now)),
    ]
    for path, text in outputs:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text if text.endswith("\n") else text + "\n")
        print("wrote %s" % os.path.relpath(path, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
