#!/usr/bin/env python3
"""generate_status_stubs.py -- SHP-7: retire the abandoned manual status docs.

SHP-7 of the status/history plane-separation design
(evidence/planning/status_history_plane_separation_design.md, Sec.1 "Two doc
populations, unlabelled" + status table Sec.7).

Kills the third "looks-maintained-but-isn't" doc category. Three docs had NO
generator owning them and were rotting silently -- a cold-start reader (human or
agent) could not tell stale hand-prose from current state. This script becomes
their owner: it regenerates each one, GENERATED-marked and timestamped, every
governance run, so currency is never in doubt.

  - evidence/GOVERNANCE_STATE.md  last hand-touched 2026-03 (V1/V2 era). Its
        "current governance state" is now derived continuously by the governance
        pipeline; the closed SD-001/002/003 substrate-debt register and the Q-019
        three-gate hypothesis survive in the architecture docs + claims.yaml + git.
        -> RETIRED to a generated pointer stub.
  - docs/REE_overview.md          IMPL-004, now status:legacy in claims.yaml. A
        secondary orientation summary over the canonical architecture docs.
        -> RETIRED to a generated pointer stub (keeps the #impl-004 anchor so the
        claims.yaml `location:` link still resolves; keeps nav_exclude).
  - docs/index.md                 the public Jekyll (Just-the-Docs) Home page. Its
        narrative is timeless; only the dated "Latest result" block rotted.
        -> REGENERATED: narrative preserved (now owned + stamped here), the rotting
        block replaced by a live pointer to docs/CURRENT_FRONT.md. Stays a valid
        Home page (title:Home / nav_order:1).

PROMOTES / DEMOTES NOTHING. Read-only over the repo; only writes the three docs.

ORDERING CONTRACT: run in scripts/governance.sh BEFORE docs/apply_nav_frontmatter.py.
That stamper owns each docs/ page's nav frontmatter (index.md -> title:Home,
nav_order:1; REE_overview.md -> nav_exclude:true) and PRESERVES the body this script
writes, so the two co-operate: this script owns the bodies, the stamper owns the
frontmatter. GOVERNANCE_STATE.md lives under evidence/ and the nav stamper never
touches it.

ASCII-only stdout (Windows cp1252 safety). UTF-8 file bodies are fine.

Usage (from REE_assembly root, or anywhere):
    python scripts/generate_status_stubs.py
Runs automatically in scripts/governance.sh.
"""

import os
import sys
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

GOVERNANCE_STATE = os.path.join(ROOT, "evidence", "GOVERNANCE_STATE.md")
REE_OVERVIEW = os.path.join(ROOT, "docs", "REE_overview.md")
INDEX = os.path.join(ROOT, "docs", "index.md")

GEN_MARK = ("<!-- GENERATED FILE -- do not edit by hand. "
            "Regenerated by scripts/generate_status_stubs.py (SHP-7). -->")


def render_governance_state(now):
    """evidence/GOVERNANCE_STATE.md -- retired to a live-source pointer stub."""
    return """# Governance State -- RETIRED (generated stub)

%s

> **GENERATED -- do not edit by hand.** Regenerated by
> `scripts/generate_status_stubs.py` (runs in `scripts/governance.sh`).  \n> Generated: %s

This file was a hand-maintained snapshot last meaningfully updated **2026-03**
(the V1/V2 era). It is **retired**: its "current governance state" is now derived
continuously by the governance pipeline. Do not read the old prose as current --
it no longer has a maintainer, and the live state lives in the sources below.

## Where the live governance state is now

- Promotion / demotion recommendations (incl. synthetic-data flags):
  [experiments/promotion_demotion_recommendations.md](experiments/promotion_demotion_recommendations.md)
- Experiments awaiting review:
  [experiments/pending_review.md](experiments/pending_review.md)
- Evidence matrix / per-claim run counts:
  [experiments/INDEX.md](experiments/INDEX.md)
- Closure rollup + drift:
  [planning/closure_status.md](planning/closure_status.md) /
  [planning/closure_drift.md](planning/closure_drift.md)
- The single live front of progress:
  [../docs/CURRENT_FRONT.md](../docs/CURRENT_FRONT.md)
- Claim registry (status of every claim):
  [../docs/claims/claims.yaml](../docs/claims/claims.yaml)

## What the retired content was (and where it lives now)

- The V1/V2 genuine-evidence corpus snapshot + per-claim run counts -- superseded
  by the live evidence matrix (`experiments/INDEX.md`, `claim_evidence.v1.json`).
- The synthetic-contamination flag -- now emitted per-claim in
  `experiments/promotion_demotion_recommendations.md`.
- The SD-001 / SD-002 / SD-003 substrate-debt register (all **closed** in ree-v2)
  -- captured in the architecture docs (`docs/architecture/*`) and
  `docs/changelog.md`.
- The Q-019 three-gate basal-ganglia hypothesis -- registered as claim **Q-019**
  (`docs/claims/claims.yaml`) and documented in
  `docs/architecture/three_loop_learning_channels.md`,
  `docs/architecture/agency_responsibility_flow.md`, and related pages.

The full prior hand-written text remains in this path's **git history**.
""" % (GEN_MARK, now)


def render_ree_overview(now):
    """docs/REE_overview.md -- retired to a canonical-sources pointer stub.

    Keeps the #impl-004 anchor (claims.yaml IMPL-004 `location:` links here) and
    the nav_exclude frontmatter (matches apply_nav_frontmatter.py TOP_EXCLUDE).
    """
    return """---
nav_exclude: true
---

# REE Overview -- RETIRED (generated stub)

%s
<a id="impl-004"></a>

> **GENERATED -- do not edit by hand.** Regenerated by
> `scripts/generate_status_stubs.py` (runs in `scripts/governance.sh`).  \n> Generated: %s

This was a secondary, hand-maintained orientation summary (claim **IMPL-004**, now
`status: legacy` in `docs/claims/claims.yaml`). It is **retired** so there is not a
second, silently-drifting copy of the canonical architecture. Read the canonical
sources instead:

## Orientation -- canonical sources

- **Why REE exists / the axioms:**
  [Foundations](architecture/five_axioms_foundations.md)
- **How the architecture is derived from ethics:**
  [Why This Architecture?](architecture/ethical_agency_derivation.md)
- **Why alignment must live inside the generator:**
  [Post-Hoc Filter Insufficiency](architecture/post_hoc_filter_insufficiency.md)
- **Component architecture:** [Architecture overview](architecture/overview.md) ->
  [E1](architecture/e1.md), [E2](architecture/e2.md), [E3](architecture/e3.md),
  [Control Plane](architecture/control_plane.md),
  [Hippocampal Systems](architecture/hippocampal_systems.md)
- **Site home / alignment framing:** [Home](index.md)
- **Programme phases + current experiment state:** [Roadmap](roadmap.md)
- **The single live front of progress:** [CURRENT_FRONT.md](CURRENT_FRONT.md)
- **Registered claims:** [Claims index](claims/claim_index.md) /
  [claims.yaml](claims/claims.yaml)
""" % (GEN_MARK, now)


# The public home page narrative below is TIMELESS (axioms, alignment framing,
# where-to-start routing). It is owned + stamped HERE so it is no longer unowned
# hand-prose; the one element that rotted -- a dated "Latest result" block -- is
# replaced by a live pointer to the generated CURRENT_FRONT.md. Edit the home page
# by editing THIS template, not docs/index.md (which is regenerated every run).
INDEX_BODY = """# Reflective-Ethical Engine

REE is a research programme with a single organising question:

**What architecture does an agent need in order to act ethically -- and can that
architecture be derived from first principles rather than designed by hand?**

The shortest alignment-facing summary is this: **REE relocates alignment from
post-hoc judgement into the generative machinery of agency.** Harm modelling,
agency attribution, goal persistence, uncertainty, and care should shape the
state from which candidate futures are generated, not merely score or filter
those futures after generation.

Most attempts to build ethical AI work by specifying desired behaviour and
training toward it. REE takes a different approach: starting from the minimum
commitments an agent must make if it is to act in a world at all -- that it
exists, that the world can harm it, that others exist and are like it -- and
asking what computational structures those commitments strictly require. The
architecture follows from the requirements. It is not a design; it is a derivation.

REE argues that ethical agency requires specific computational capacities, not
just rules or reward shaping. An agent must be able to distinguish self from
world and self from other, separate imagined action from real action, attribute
responsibility for its effects, learn from mistakes, and keep care structurally
live in how it evaluates trajectories. On this view, ethical behaviour is not
something added on top of intelligence, but something that depends on the right
substrate for accountable action.

Computational psychiatry is one of REE's main validation paths. If those
capacities are genuinely required, then their failure should produce
recognizable regime breakdowns rather than arbitrary errors: depression,
dementia, OCD, mania, psychosis, and related disturbances can be understood as
failures in the same substrate that underwrites agency, responsibility, and
care. Psychiatry is therefore not separate from the project, but one of the
main ways its architectural claims can be tested.

---

## What the derivation found

Starting from a handful of foundational axioms and working through what
comparator functions ethical agency cannot do without, the architecture that
follows includes a persistent world model, a fast transition predictor, a
harm accumulator with a reset condition, a commit gate tied to genuine
uncertainty, and a multi-step planning mechanism that can model others' harm
and goals in the same terms as its own.

This is not a long list of components chosen to cover the design space. It is
a short list of structures that cannot be absent without losing the capacity
for ethical action. Remove any one and a specific ethical function disappears.

**When cross-checked against neuroscience, this architecture maps -- without
having been built to fit -- onto most major brain structures and their known
functional roles.** The offline consolidation phase the mathematics requires
matches the two-stage sleep architecture. The commitment gate maps to the
basal ganglia circuit. The harm accumulator maps to the cingulate and its
modulation by serotonin. The convergence was found after the derivation,
not before it.

**When the missing structures are identified as failure modes, they match
clinical psychopathology.** Absent harm accumulator: features of anhedonia
and chronic pain. Closed attribution loop: passivity phenomena. Precision
dysregulation: psychosis-like states. The failures occur at the same
positions in biological and artificial systems because they are both
instantiations of the same necessary architecture -- or its absence.

---

## The alignment implication

Current AI systems are trained to pursue proxies for what ethical agency
requires. The proxies are often good. But much of the alignment work sits
outside or downstream of the machinery that generates action: output scoring,
critique, filtering, preference optimisation, or post-hoc explanation.

REE treats that as the wrong location for the work. The architecture that
ethical agency requires must make constraint-relevant content active during
state construction, trajectory generation, commitment gating, and consequence
memory. A sufficiently capable optimiser can learn to satisfy or explain a
proxy while leaving the generator unchanged; it cannot bypass a comparator that
is constitutive of how futures become available for action.

Scaling capability over an architecture that lacks the necessary comparators
does not introduce those comparators. The failure modes that emerge at scale
are predictable from the absences.

This is a different claim from "we need better specifications." It is a
claim about what kind of problem alignment is.

---

## Where to start

**If you are new to REE:**
[Why This Architecture?](architecture/ethical_agency_derivation.md) --
the derivation in full; the cognifold motif; why the brain result matters

**If you want the alignment framing first:**
[Post-Hoc Filter Insufficiency](architecture/post_hoc_filter_insufficiency.md) --
why REE argues that safety and ethical content must be active inside trajectory
generation, not only available to a judge after generation

**If you want the foundational argument:**
[Foundations](architecture/five_axioms_foundations.md) --
the irreducible axioms from which the architecture follows; derived ethical objectives

**If you want the relation to established ethics:**
[Established ethical systems](architecture/established_ethical_systems.md) --
how autonomy, justice, rights, care, sustainability, uncertainty ethics, and other
traditions can be read as derived stabilisations of the REE substrate

**If you want the component architecture:**
[Architecture overview](architecture/overview.md) -- then
[Founder ontology (E1/E2/E3 intent)](architecture/founder_ontology.md),
[E1](architecture/e1.md), [E2](architecture/e2.md),
[E3](architecture/e3.md), [Control Plane](architecture/control_plane.md),
[Hippocampal Systems](architecture/hippocampal_systems.md),
[Brain map](architecture/brain_map.md) (`/brain-map` in the explorer)

**If you want later-version scaling needs:**
[Architecture scaling needs](architecture/architecture_scaling_needs.md) --
derived scaling versus deliberately scaled intelligence levers

**If you want V4 planning:**
[V4 planning index](architecture/v4_planning_index.md) --
the V4 spec, object/entity permanence harness, V3/V4 boundary documents,
and open documentation gaps in one place

**If you want what this predicts and where it is tested:**
[Roadmap](roadmap.md) -- programme phases and current experimental state

**If a term is unfamiliar:**
[Glossary](glossary.md) -- canonical terminology; start here before component docs

**If you want to contribute compute:**
[Contribute](contribute.html) -- no account needed; experiments run on donated GPU time

---

## The current front

For the single live front of progress -- what is being built and tested right now,
with no history mixed in -- see the generated
[Current Front](CURRENT_FRONT.md).

Narrative history of landed results lives in the [changelog](changelog.md).

---

## Claims and evidence

REE claims are typed (INV / ARC / MECH / Q / IMPL), registered with confidence
scores, and governed through an experiment-evidence pipeline.

[Claims index](claims/claim_index.md) -- all registered claims with status and dependencies

---

## Related frameworks

**[REE vs. Neural Computers (Meta AI / KAUST)](architecture/comparisons/meta_kaust_neural_computers.md)**
The Neural Computers programme (Schmidhuber et al., 2025) proposes unifying
computation, memory, and I/O as a single learned runtime. Their four
requirements for a Completely Neural Computer -- Turing completeness, universal
programmability, behavior consistency, and machine-native semantics -- map
directly onto structures REE derives from first principles. The comparison
document shows the cross-walk.

---

## Implementation substrates

| Substrate | Role |
|-----------|------|
| ree-v3 | Active -- primary implementation and experiment substrate |
| ree-v2 | Complete -- 15 experiments; triggered the V3 transition |
| ree-v1-minimal | Active baseline / parity substrate |
"""


def render_index(now):
    """docs/index.md -- regenerated public Home page (nav frontmatter first)."""
    frontmatter = "---\ntitle: Home\nnav_order: 1\n---\n"
    header = ("%s\n<!-- Home page body is owned + regenerated by "
              "scripts/generate_status_stubs.py (SHP-7); Generated: %s. "
              "Edit the INDEX_BODY template in that script, not this file. "
              "apply_nav_frontmatter.py owns the frontmatter above. -->\n"
              % (GEN_MARK, now))
    return frontmatter + header + "\n" + INDEX_BODY


def main():
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    outputs = [
        (GOVERNANCE_STATE, render_governance_state(now)),
        (REE_OVERVIEW, render_ree_overview(now)),
        (INDEX, render_index(now)),
    ]
    for path, text in outputs:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text if text.endswith("\n") else text + "\n")
        print("wrote %s" % os.path.relpath(path, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
