#!/usr/bin/env python3
"""
Refresh generated_at_utc timestamps in governance_agenda.v1.json.

Called by governance.sh after the evidence pipeline runs, so the REE Claims
Explorer banner always shows the correct "last gov run" date.

governance_agenda.v1.json is generated by run_governance_cycle.py (the full
adjudication cycle script). governance.sh runs more frequently for evidence
ingestion only. This script patches just the timestamp fields so the explorer
date stays current without running the full cycle.
"""

import re
import sys
from datetime import datetime, timezone
from pathlib import Path

AGENDA_PATH = Path("evidence/planning/governance_agenda.v1.json")


def main() -> int:
    if not AGENDA_PATH.exists():
        print(f"WARNING: {AGENDA_PATH} not found -- skipping timestamp refresh")
        return 0

    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    text = AGENDA_PATH.read_text(encoding="utf-8")

    text, n1 = re.subn(
        r'"generated_at_utc":\s*"[^"]*"',
        f'"generated_at_utc": "{now}"',
        text,
    )
    text, n2 = re.subn(
        r'"last_run_generated_at_utc":\s*"[^"]*"',
        f'"last_run_generated_at_utc": "{now}"',
        text,
    )

    AGENDA_PATH.write_text(text, encoding="utf-8")
    print(
        f"Refreshed governance_agenda.v1.json timestamps to {now}"
        f" ({n1} generated_at_utc, {n2} last_run_generated_at_utc)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
